apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fb.name" . }}-nginx
  labels:
    {{- include "fb.labels" . | nindent 4 }}
data:
  default.conf: |-
{{ .Files.Get "files/nginx.conf" | indent 4 }}
