{{- range .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
  target: { name: {{ .name }}, creationPolicy: Owner }
  dataFrom:
    - extract: { key: {{ .remoteRef }} }
---
{{- end }}
