apiVersion: v1
kind: Service
metadata:
  name: {{ include "fb.name" . }}
  labels:
    {{- include "fb.labels" . | nindent 4 }}
spec:
  selector: { app.kubernetes.io/name: {{ include "fb.name" . }} }
  ports: [ { name: http, port: {{ .Values.service.port }}, targetPort: http } ]
